### ISSUE TITLE
Add flatMap to PlayStreamIterator trait

### ISSUE THREAD

**Issue by malcolmgreaves** [Nitro/streamcollections#5]
It would be excellent to have the ability to perform a flatMap on a steam. Relevant versions would include Option, Future, and Try types. I'd take some time to implement this feature, if it would be a welcome addition.

**Comment by mkolod** [comment]
For sure! I raised it earlier, I think everyone liked the idea, but there was no bandwidth to do it. So, thumbs up from me! :)

**Comment by malcolmgreaves** [comment]
PR #6 solves this issue.

**Comment by malcolmgreaves** [comment]
PR meged. Closing.
